[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'Shougo/vimshell'

[[plugins]]
repo = 'sheerun/vim-polyglot'

[[plugins]] # ステータスバー
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'ryanoasis/vim-devicons'

[[plugins]]
repo = 'delphinus/lightline-delphinus'

[[plugins]] # gitの変更点
repo = 'airblade/vim-gitgutter'

# [[plugins]]
# repo = 'neomake/neomake'
# hook_add = '''
#   autocmd! BufWritePost,BufEnter * Neomake
# '''

[[plugins]]
repo = 'w0rp/ale'

[[plugins]]
repo = 'Yggdroot/indentLine'

[[plugins]] # カラースキーマ
repo = 'chriskempson/vim-tomorrow-theme'

# [[plugins]] # カラースキーマ
# repo = 'w0ng/vim-hybrid'
