[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'Shougo/vimshell'

[[plugins]]
repo = 'sheerun/vim-polyglot'

[[plugins]] # ステータスバー
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'ryanoasis/vim-devicons'

[[plugins]]
repo = 'delphinus/lightline-delphinus'

[[plugins]] # gitの変更点
repo = 'mhinz/vim-signify'

[[plugins]]
repo = 'thinca/vim-ref'

[[plugins]]
repo = 'Yggdroot/indentLine'

[[plugins]]
repo = 'w0rp/ale'

[[plugins]] # カラースキーマ
repo = 'chriskempson/vim-tomorrow-theme'

# [[plugins]] # カラースキーマ
# repo = 'w0ng/vim-hybrid'

################################################
# Oni
################################################
[[plugins]]
repo = 'wellle/targets.vim'

[[plugins]] # コメント機能
repo = 'tpope/vim-commentary'

[[plugins]]
repo ='tpope/vim-surround'

[[plugins]]
repo = 'tpope/vim-unimpaired'
