[[plugins]]
repo = 'Shougo/neomru.vim'
on_if = 1

[[plugins]]
repo = 'jiangmiao/auto-pairs'
on_i = 1

[[plugins]]
repo = 'Shougo/neoyank.vim'
on_if = 1
on_event = 'TextYankPost'
on_source = 'unite.vim'

[[plugins]]
repo = 'Shougo/neosnippet'
depends = ['neosnippet-snippets']
on_i = 1
on_ft = ['snippet']

[[plugins]]
repo = 'Shougo/neocomplete.vim'
if = 'has("lua")'
on_i = 1

[[plugins]]
repo = 'Shougo/deoplete.nvim'
if = 'has("nvim")'
on_i = 1

[[plugins]]
repo = 'Shougo/unite.vim'
depends = 'neomru.vim'

[[plugins]]
repo = 'ConradIrwin/vim-bracketed-paste'
on_i = 1

[[plugins]]
repo = 'scrooloose/nerdtree'
on_cmd = ['<C-e>', 'NERDtree']

# [[plugins]]
# repo = 'ctrlpvim/ctrlp.vim'
# on_cmd    = ['CtrP']

# [[plugins]]
# repo = 'rhysd/devdocs.vim'
# on_cmd = ['DevDocs']
# on_map = ['<Plug>(devdocs-under-cursor)']

[[plugins]]
repo = 'thinca/vim-quickrun'
on_cmd = ['QuickRun']
on_map = ['<Plug>(quickrun)']

################################################
# Ruby
################################################

[[plugins]] # def end の自動入力
repo = 'tpope/vim-endwise.git'
on_ft = 'ruby'

[[plugins]] # Railsプロジェクト用プラグイン
repo = 'tpope/vim-rails'
on_ft = 'ruby'

[[plugins]]
repo = 'kchmck/vim-coffee-script'
on_ft = 'coffee'

################################################
# Other Files
################################################

# [[plugins]] # markdownのtableの整形
# repo = 'godlygeek/tabular'
# on_ft = ['markdown', 'mkd', 'md']

[[plugins]] # markdownのクゥオート内シンタックス
repo = 'joker1007/vim-markdown-quote-syntax'
on_ft = ['markdown', 'mkd', 'md']

# [[plugins]] # markdownのPreview
# repo = 'kannokanno/previm'
# on_ft = ['markdown', 'mkd', 'md']

# [[plugins]] # ブラウザ起動
# repo = 'tyru/open-browser.vim'
# on_ft = ['markdown', 'mkd', 'md']

[[plugins]]
repo = 'lilydjwg/colorizer'
on_ft = ['html', 'css', 'sass', 'scss']
