[[plugins]]
repo = 'Shougo/denite.nvim'
on_cmd = 'Denite'
depends = ['neomru.vim']
if = 'has("python3")'
hook_source = 'source ~/.config/nvim/plugins-denite.vim'

[[plugins]]
repo = 'Shougo/neomru.vim'
on_source = ['denite.nvim']

[[plugins]]
repo      = 'Jagua/vim-denite-ghq'
on_source = ['denite.nvim']

[[plugins]]
repo = 'Shougo/deoplete.nvim'
if = 'has("nvim")'
on_i = 1
hook_source = '''
  let g:deoplete#enable_at_startup = 1
  let g:deoplete#auto_complete_delay = 0
'''

[[plugins]]
repo = 'jiangmiao/auto-pairs'
on_i = 1

[[plugins]]
repo = 'ConradIrwin/vim-bracketed-paste'
on_i = 1

[[plugins]]
repo = 'scrooloose/nerdtree'
on_cmd = ['<C-e>', 'NERDtree']
hook_source = '''
  noremap <silent> <C-e> :NERDTree<CR>
'''

[[plugins]]
repo = 'rhysd/devdocs.vim'
on_cmd = ['DevDocs']
on_map = ['<Plug>(devdocs-under-cursor)']
hook_source = '''
  nmap K <Plug>(devdocs-under-cursor)
'''

[[plugins]]
repo = 'thinca/vim-quickrun'
on_cmd = ['QuickRun']
on_map = ['<Plug>(quickrun)']

################################################
# Ruby
################################################

[[plugins]] # def end の自動入力
repo = 'tpope/vim-endwise.git'
on_ft = 'ruby'

[[plugins]] # Railsプロジェクト用プラグイン
repo = 'tpope/vim-rails'
on_ft = ['ruby', 'haml']

[[plugins]] # ローカル変数ハイライト
repo = 'todesking/ruby_hl_lvar.vim'
on_ft = 'ruby'
if = 'has("ruby")'

[[plugins]]
repo = 'kchmck/vim-coffee-script'
on_ft = 'coffee'


################################################
# JS
################################################

[[plugins]]
repo = 'othree/yajs.vim'
on_ft = ['javascript', 'javascript.jsx', 'typescript', 'typescript.tsx']

[[plugins]]
repo = 'HerringtonDarkholme/yats.vim'
on_ft = ['typescript', 'typescript.tsx']

[[plugins]]
repo = 'mxw/vim-jsx'
on_ft = ['javascript', 'javascript.jsx', 'typescript', 'typescript.tsx']

################################################
# Other Files
################################################

[[plugins]] # markdownのクゥオート内シンタックス
repo = 'joker1007/vim-markdown-quote-syntax'
on_ft = ['markdown', 'mkd', 'md']

# [[plugins]] # markdownのPreview
# repo = 'kannokanno/previm'
# on_ft = ['markdown', 'mkd', 'md']

# [[plugins]] # ブラウザ起動
# repo = 'tyru/open-browser.vim'
# on_ft = ['markdown', 'mkd', 'md']

[[plugins]]
repo = 'lilydjwg/colorizer'
on_ft = ['html', 'css', 'sass', 'scss']
