[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'kien/ctrlp.vim'

[[plugins]]
repo = 'yanktmp.vim'

[[plugins]]
repo = 'rhysd/devdocs.vim'

################################################
# HTML CSS Javascript
################################################

[[plugins]] # html5のコードをシンタックス表示する
repo  = 'hail2u/vim-css3-syntax'
on_ft = ['css', 'javascript', 'html']

[[plugins]] # vimにjsのシンタックスを追加する
repo  = 'pangloss/vim-javascript'
on_ft = 'javascript'

[[plugins]] # jsxのシンタックス
repo = 'mxw/vim-jsx'
on_ft = 'javascript'

################################################
# Ruby
################################################

[[plugins]] # def end の自動入力
repo = 'tpope/vim-endwise.git'
on_ft = 'ruby'

[[plugins]] # 対応括弧へのカーソル移動機能
repo = 'ruby-matchit'
on_ft = 'ruby'

[[plugins]] #
repo = 'vim-ruby/vim-ruby'
on_ft = 'ruby'

[[plugins]] # Railsプロジェクト用プラグイン
repo = 'taichouchou2/vim-rails'
on_ft = 'ruby'

[[plugins]] # Railsプロジェクト用プラグイン
repo = 'romanvbabenko/rails.vim'
on_ft = 'ruby'

[[plugins]] # RSpecをvimから実行
repo = 'thoughtbot/vim-rspec'
on_ft = 'ruby'

################################################
# Other Files
################################################

[[plugins]] # markdownのシンタックス
repo = 'rcmdnk/vim-markdown'
on_ft = ['markdown', 'mkd']

[[plugins]] # markdownのtableの整形
repo = 'godlygeek/tabular'
on_ft = ['markdown', 'mkd']

[[plugins]] # markdownのクゥオート内シンタックス
repo = 'joker1007/vim-markdown-quote-syntax'
on_ft = ['markdown', 'mkd']

[[plugins]] # markdownのPreviewス
repo = 'kannokanno/previm'
on_ft = ['markdown', 'mkd']

[[plugins]] # ブラウザ起動
repo = 'tyru/open-browser.vim'
on_ft = ['markdown', 'mkd']

[[plugins]] # tomlのシンタックス
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]] # jsonのシンタックス
repo = 'elzr/vim-json'
on_ft = 'json'
