[[plugins]]
repo = 'jiangmiao/auto-pairs'
on_i = 1

[[plugins]]
repo = 'ConradIrwin/vim-bracketed-paste'
on_i = 1

[[plugins]]
repo = 'preservim/nerdtree'
on_cmd = ['<C-e>', 'NERDtree']
hook_add = '''
  noremap <silent> <C-e> :NERDTree<CR>
'''

[[plugins]]
repo = 'thinca/vim-quickrun'
on_cmd = ['QuickRun']
on_map = ['<Plug>(quickrun)']

################################################
# Ruby
################################################

[[plugins]] # def end の自動入力
repo = 'tpope/vim-endwise.git'
on_ft = 'ruby'

[[plugins]] # Railsプロジェクト用プラグイン
repo = 'tpope/vim-rails'
on_ft = ['ruby', 'haml', 'eruby']

[[plugins]]
repo = 'tpope/vim-haml'
on_ft = 'haml'

################################################
# JS
################################################

# [[plugins]]
# repo = 'othree/yajs.vim'
# on_ft = ['javascript', 'typescript']

################################################
# Elixir
################################################

[[plugins]]
repo = 'elixir-editors/vim-elixir'
on_ft = ['elixir']

[[plugins]]
repo = 'mhinz/vim-mix-format'
on_ft = ['elixir']
hook_source = '''
  let g:mix_format_on_save = 1
'''

################################################
# Rust
################################################

[[plugins]]
repo = 'rust-lang/rust.vim'
on_ft = ['rust']
hook_source = '''
  let g:rustfmt_autosave = 1
'''

################################################
# Go
################################################

[[plugins]]
repo = 'fatih/vim-go'
on_ft = ['go']

################################################
# Other Files
################################################

[[plugins]] # markdownのクゥオート内シンタックス
repo = 'joker1007/vim-markdown-quote-syntax'
on_ft = ['markdown', 'mkd', 'md']

[[plugins]]
repo = 'lilydjwg/colorizer'
on_ft = ['html', 'css', 'sass', 'scss']
