[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'sheerun/vim-polyglot'

[[plugins]]
repo = 'neoclide/coc.nvim'
if = '''executable('node') && executable('yarn')'''
rev = 'release'
merged = '0'
hook_add = '''
let g:coc_global_extensions = [
  \ 'coc-solargraph',
  \ 'coc-tsserver',
  \ 'coc-spell-checker'
  \ ]
'''

[[plugins]] # ステータスバー
repo = 'itchyny/lightline.vim'

# [[plugins]]
# repo = 'ryanoasis/vim-devicons'

[[plugins]]
repo = 'rebelot/kanagawa.nvim'
hook_add = '''
" colorscheme 設定は source 後に行う必要があるので VimEnter で行う。
" 但し Colorscheme イベントの発生が抑制されないよう nented を付ける。
au MyAutoCmd VimEnter * nested colorscheme kanagawa
'''

[[plugins]]
repo = 'delphinus/lightline-delphinus'

[[plugins]]
repo = 'nanotee/zoxide.vim'

[[plugins]]
repo = 'junegunn/fzf'
build = './install --all'
merged = 0

[[plugins]]
repo = 'junegunn/fzf.vim'
depends = 'fzf'

[[plugins]] # gitの変更点
repo = 'mhinz/vim-signify'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
# brew install lynx to use webdict
repo = 'thinca/vim-ref'
hook_add = '''
  let g:ref_open = 'vsplit'
  let g:ref_refe_cmd = $HOME.'/.asdf/shims/refe'

  let g:ref_source_webdict_sites = {
  \   'wikipedia:ja': 'http://ja.wikipedia.org/wiki/%s',
  \   'weblio': 'http://ejje.weblio.jp/content/%s',
  \   'alc': 'https://eow.alc.co.jp/search?q=%s',
  \ }

  nnoremap ,rr :<C-U>Ref refe<Space>
'''

[[plugins]]
repo = 'szw/vim-tags'

[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'
hook_add = '''
  let g:indent_guides_enable_on_vim_startup = 1
  let g:indent_guides_start_level = 2
  let g:indent_guides_guide_size = 1
  let g:indent_guides_exclude_filetypes = ['help', 'nerdtree', 'denite']
  hi IndentGuidesOdd  ctermbg=darkgrey
  hi IndentGuidesEven ctermbg=black
'''

[[plugins]]
repo = 'w0rp/ale'
hook_add = '''
  let g:ale_lint_on_enter = 0
  let g:ale_fix_on_save = 1
  let g:ale_sign_column_always = 1
  let g:ale_completion_enabled = 1
  let g:lightline_delphinus_colorscheme='nord_improved'
  let g:ale_javascript_prettier_options = '--no-semi --single-quote --jsx-single-quote --trailing-comma none'

  let g:ale_linters = {
        \ 'ruby': ['rubocop'],
        \ 'javascript': ['eslint'],
        \ 'typescript': ['eslint'],
        \ 'elixir': ['mix'],
        \ 'rust': ['cargo'],
        \ 'go': ['golint'],
        \ 'python': ['pylint']
        \ }

let g:ale_fixers = {
        \ '*': ['remove_trailing_lines', 'trim_whitespace'],
        \ 'javascript': ['prettier'],
        \ 'javascriptreact': ['prettier'],
        \ 'typescript': ['prettier'],
        \ 'typescriptreact': ['prettier'],
        \ 'go': ['gofmt']
        \ }

  autocmd BufRead,BufNewFile *.erb set filetype=eruby.html
  autocmd BufNewFile,BufRead *.md set filetype=markdown
  autocmd BufNewFile,BufRead *.scss set filetype=css
  autocmd BufNewFile,BufRead *.jsx set filetype=javascript.jsx
  autocmd BufNewFile,BufRead *.tsx set filetype=typescript.tsx
  let g:polyglot_disabled = ['markdown']
'''

[[plugins]] # カラースキーマ
repo = 'chriskempson/base16-vim'

################################################
# Oni
################################################

[[plugins]]
repo = 'wellle/targets.vim'

[[plugins]] # コメント機能
repo = 'tpope/vim-commentary'

# [[plugins]]
# repo ='tpope/vim-surround'

# [[plugins]]
# repo = 'tpope/vim-unimpaired'

################################################
# deno
################################################

[[plugins]]
repo = 'vim-denops/denops.vim'

[[plugins]]
repo = 'vim-denops/denops-helloworld.vim'
