export LANG=ja_JP.UTF-8
export LC_ALL=ja_JP.UTF-8
export LC_CTYPE=ja_JP.UTF-8

### Added by Zinit's installer
if [[ ! -f $HOME/.local/share/zinit/zinit.git/zinit.zsh ]]; then
    print -P "%F{33} %F{220}Installing %F{33}ZDHARMA-CONTINUUM%F{220} Initiative Plugin Manager (%F{33}zdharma-continuum/zinit%F{220})…%f"
    command mkdir -p "$HOME/.local/share/zinit" && command chmod g-rwX "$HOME/.local/share/zinit"
    command git clone https://github.com/zdharma-continuum/zinit "$HOME/.local/share/zinit/zinit.git" && \
        print -P "%F{33} %F{34}Installation successful.%f%b" || \
        print -P "%F{160} The clone has failed.%f%b"
fi

source "$HOME/.local/share/zinit/zinit.git/zinit.zsh"
autoload -Uz _zinit
(( ${+_comps} )) && _comps[zinit]=_zinit

# Load a few important annexes, without Turbo
# (this is currently required for annexes)
zinit light-mode for \
   zdharma-continuum/zinit-annex-as-monitor \
   zdharma-continuum/zinit-annex-bin-gem-node \
   zdharma-continuum/zinit-annex-patch-dl \
   zdharma-continuum/zinit-annex-rust
### End of Zinit's installer chunk

zinit light zsh-users/zsh-autosuggestions
zinit light zdharma-continuum/fast-syntax-highlighting
zinit light nickbradley/aw-watcher-shell
zinit ice blockf; zinit load zsh-users/zsh-completions

eval "$(zoxide init zsh)"

# === PROMPT ===
eval "$(starship init zsh)"
# /=== PROMPT ===

HISTFILE=$HOME/.zsh_history           # 履歴をファイルに保存する
HISTSIZE=100000                       # メモリ内の履歴の数
SAVEHIST=100000                       # 保存される履歴の数
setopt extended_history
setopt append_history
function history-all { history -E 1 } # 全履歴の一覧を出力する

setopt auto_list
setopt hist_ignore_dups
setopt hist_no_store
setopt hist_reduce_blanks

export XDG_CONFIG_HOME=$HOME/.config

alias ls='ls -vG'
alias cp="cp -p"
alias mv="mv -i"
alias rm="rm -i"
alias vi="nvim"
alias g='cd ~/ghq/$(ghq list | peco)'
alias gits="git status"
alias gitb="git branch"
alias gitc="git checkout"
alias gitsw="git switch"
alias gitpf="git push --force-with-lease"
alias gitepr="git commit -m 'make pull request' --allow-empty"
alias gitai='git commit -t <(git diff --staged | aichat -r commit)'
alias t='todo.sh -t -d ~/Dropbox/PlainText/.todo.cfg'
alias remem='du -sx / &> /dev/null & sleep 25 && kill $!'
alias be='bundle exec'
alias bes='bundle exec sidekiq -C config/sidekiq.yml'
alias ber='bundle exec rspec'
alias tailscale="/Applications/Tailscale.app/Contents/MacOS/Tailscale"

# Base16 Shell
# BASE16_SHELL="$HOME/.config/base16-shell/"
# [ -n "$PS1" ] && \
# [ -s "$BASE16_SHELL/profile_helper.sh" ] && \
# eval "$("$BASE16_SHELL/profile_helper.sh")"

# gitignore ex: gi ruby >> .gitignore
# function gi() { curl https://www.gitignore.io/api/$@ ;}

# brew
export HOMEBREW_NO_ANALYTICS=1

# Autostart if not already in tmux.
# if [[ ! -n $TMUX && $- == *l* ]]; then
#   # get the IDs
#   ID="`tmux list-sessions`"
#   if [[ -z "$ID" ]]; then
#     tmux new-session
#   fi
#   create_new_session="Create New Session"
#   ID="$ID\n${create_new_session}:"
#   ID="`echo $ID | peco | cut -d: -f1`"
#   if [[ "$ID" = "${create_new_session}" ]]; then
#     tmux new-session
#   elif [[ -n "$ID" ]]; then
#     tmux attach-session -t "$ID"
#   else
#     :  # Start terminal normally
#   fi
# fi

# m1 mac
if [[ $(arch) == 'arm64' ]]; then
  export PATH="$HOME/bin:/opt/homebrew/bin:/opt/homebrew/sbin:$PATH"
  # export LDFLAGS="-L/opt/homebrew/opt/libpq/lib"
  # export CPPFLAGS="-I/opt/homebrew/opt/libpq/include"
  # export PKG_CONFIG_PATH="/opt/homebrew/opt/libpq/lib/pkgconfig"
  export SHELL_ARCH="arm64"
  echo '🚀 arm64 '
else
  export PATH="$HOME/bin:/usr/local/bin:/usr/local/sbin:$PATH"
  export SHELL_ARCH="x86"
  echo '👋 x86 '
fi

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

export PATH="$PATH:/Users/masumi/.foundry/bin"

# __NSPlaceholderDictionary
export OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES

export RUBYOPT=--yjit

eval "$(mise activate zsh)"

# pnpm
export PNPM_HOME="/Users/masumi/Library/pnpm"
case ":$PATH:" in
  *":$PNPM_HOME:"*) ;;
  *) export PATH="$PNPM_HOME:$PATH" ;;
esac
# pnpm end

alias claude="/Users/masumi/.claude/local/claude"

[[ "$TERM_PROGRAM" == "kiro" ]] && . "$(kiro --locate-shell-integration-path zsh)"
